In [153]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

In [54]:
LIBORrate = pd.read_csv("libor.csv").set_index('date')[:12]
LIBORrate

SWAPrate = pd.read_csv('swap.csv').set_index('date')[:12]
SWAPrate

W2      W1      W3       W4     W5      W6       W7     W8   \
date                                                                       
3/31/17   1.6176  1.3836  1.8070  1.9450  2.0523  2.1423  2.2165  2.2800   
4/28/17   1.5725  1.3900  1.7196  1.8363  1.9327  2.0162  2.0887  2.1522   
5/31/17   1.5105  1.3565  1.6398  1.7400  1.8275  1.9080  1.9775  2.0385   
6/30/17   1.6178  1.4571  1.7509  1.8616  1.9580  2.0410  2.1125  2.1650   
7/31/17   1.5987  1.4595  1.7150  1.8153  1.9077  1.9917  2.0690  2.1363   
8/31/17   1.5350  1.4385  1.6175  1.6905  1.7615  1.8324  1.8997  1.9603   
9/29/17   1.7410  1.5653  1.8578  1.9407  2.0039  2.0828  2.1414  2.1941   
10/31/17  1.8178  1.6403  1.9356  2.0190  2.0905  2.1538  2.2118  2.2614   
11/30/17  1.9705  1.7832  2.0781  2.1462  2.1990  2.2468  2.2920  2.3340   
12/29/17  2.0780  1.8992  2.1690  2.2105  2.2437  2.2765  2.3106  2.3412   
1/31/18   2.3319  2.0960  2.4684  2.5424  2.5893  2.6304  2.6617  2.6887   
2/28/18   2.5333  2.3187  2.6497  2.7124  2.7514  2.7833  2.8087  2.8332   

              W9     W10     W20    W30   
date                                      
3/31/17   2.3350  2.3841  2.6155  2.6451  
4/28/17   2.2071  2.2544  2.4844  2.5169  
5/31/17   2.0945  2.1471  2.3860  2.4238  
6/30/17   2.2318  2.2810  2.5063  2.5395  
7/31/17   2.1959  2.2483  2.5089  2.5553  
8/31/17   2.0160  2.0669  2.3279  2.3801  
9/29/17   2.2455  2.2910  2.4945  2.5334  
10/31/17  2.3102  2.3517  2.5586  2.5910  
11/30/17  2.3708  2.4055  2.5816  2.6013  
12/29/17  2.3700  2.3980  2.5345  2.5423  
1/31/18   2.7145  2.7355  2.8277  2.8128  
2/28/18   2.8547  2.8773  2.9693  2.9474

Fit the LIBOR rate

In [124]:
def func(x,a1,a2,a3,a4):
    y = (a1 + a2*x)*np.exp(- a3*x) + a4
    return y

In [130]:
xdata = np.array([0, 1, 2, 3, 6, 12])
y = [LIBORrate.iloc[i].values for i in range(12)]
np.random.seed(10000)

y_noise = [0.2 * np.random.normal(size = t_data.size) for i in range(12)]
ydata = y + y_noise
colorcurve = ['yello', 'red', 'green', 'black', 'purple', 'white', 'crimson', 'violet', 'crimson', '2.4', 'darkblue', 'brown']
[plt.plot(xdata, ydata[i], color = colorcurve[i]) for i in range(12)]

[[<matplotlib.lines.Line2D at 0x1131c1400>],

In [134]:
coef = []
for i in range(12):
    popt, pcov = curve_fit(func, xdata, ydata[i])
    print(popt)
    coef.append(popt)

[-1.0369378  -0.28158454  0.2632111   1.98881828]
[-0.98499793 -0.25503335  0.26794009  1.93549198]
[ -1.36582823e+00   1.64053936e-04   6.85329566e-02   2.32289957e+00]
[-1.09527608 -0.11430306  0.12533508  2.28675796]
[-0.92380698 -0.1135081   0.14638243  2.1219657 ]
[-1.02081002 -0.0891159   0.11789315  2.22126576]
[-0.80131863 -0.1493421   0.20409165  2.00613801]
[-0.83210852 -0.14223086  0.21659573  2.03674588]
[ -1.04482577e+00   1.89293295e-07   9.35264238e-02   2.28493263e+00]
[ -1.25161330e+00  -1.23752409e-06   5.64354911e-02   2.74033696e+00]
[ -1.18200840e+00  -5.18661087e-05   9.26076895e-02   2.65403263e+00]
[ -1.13196572e+00   6.56353001e-06   1.91276411e-01   2.60931314e+00]


Calculate swap rate 

In [135]:
coef

[array([-1.0369378 , -0.28158454,  0.2632111 ,  1.98881828]),
 array([-0.98499793, -0.25503335,  0.26794009,  1.93549198]),
 array([ -1.36582823e+00,   1.64053936e-04,   6.85329566e-02,
          2.32289957e+00]),
 array([-1.09527608, -0.11430306,  0.12533508,  2.28675796]),
 array([-0.92380698, -0.1135081 ,  0.14638243,  2.1219657 ]),
 array([-1.02081002, -0.0891159 ,  0.11789315,  2.22126576]),
 array([-0.80131863, -0.1493421 ,  0.20409165,  2.00613801]),
 array([-0.83210852, -0.14223086,  0.21659573,  2.03674588]),
 array([ -1.04482577e+00,   1.89293295e-07,   9.35264238e-02,
          2.28493263e+00]),
 array([ -1.25161330e+00,  -1.23752409e-06,   5.64354911e-02,
          2.74033696e+00]),
 array([ -1.18200840e+00,  -5.18661087e-05,   9.26076895e-02,
          2.65403263e+00]),
 array([ -1.13196572e+00,   6.56353001e-06,   1.91276411e-01,
          2.60931314e+00])]

In [165]:
tdata2 = np.array([0.5,0.25,0.75,1,1.25,1.5,1.75,2,2.25,2.5,4,7.5])
discount = []

for j in range(12):
    ydata2 = (coef[j][0] + coef[j][1]*tdata2)*np.exp( - coef[j][2]*tdata2) + coef[j][3]
    discountfactor = []
    for i in range(len(tdata2)):
        discountfactor.append(1/(ydata2/100+1)[i] ** tdata2[i])
    discount.append(discountfactor)
discountfactor

[0.99218949883706742,
 0.99621065977399847,
 0.98795678086964711,
 0.98353151966305152,
 0.97893153243330322,
 0.97417349372774609,
 0.96927298939867446,
 0.96424457020386045,
 0.95910180466945216,
 0.95385733091711478,
 0.92085753504277812,
 0.84075578775972459]

In [166]:
discountdata = pd.DataFrame(discount, columns = tdata2)
swaprate = []

for i in range(12):
    w = (1 - discountdata.loc[i][7.5])/sum(discountdata.loc[i])*100
    swaprate.append(w)
    
swaprate

[0.93177349720703873,
 0.92946368210553854,
 0.90732828126414611,
 0.91880887573205194,
 0.92219453089777792,
 0.91875036389516851,
 0.9568538320565787,
 0.99834087736472188,
 1.0585742240915246,
 1.1478488032193459,
 1.228061695841302,
 1.3821982298341331]

Compute MTM values of the swaps (time series of swaps)

In [167]:
MTMvalues = pd.DataFrame(discount)[0] * swaprate
MTMvalues

0     0.927350
1     0.925023
2     0.902811
3     0.913326
4     0.916663
5     0.913211
6     0.951093
7     0.992276
8     1.051823
9     1.139203
10    1.218801
11    1.371403
Name: 0, dtype: float64

Compute DV01s (time series of swaps)

In [168]:
tdata3 = np.array([0.5,0.25,0.75,1,1.25,1.5,1.75,2,2.25,2.5,4,7.5])
discount2 = []

for k in range(12):
    ydata3 = (coef[k][0] + coef[k][1]*tdata3)*np.exp( - coef[k][2]*tdata3) + coef[k][3]
    discountfactor2 = []
    for i in range(len(tdata3)):
        discountfactor2.append(1/(ydata2/100 + 1 + 0.0001)[i] ** tdata3[i])
    discount2.append(discountfactor2)
    
discountfactortable = pd.DataFrame(discount2, columns = tdata3)
discountfactortable

0.50      0.25      0.75      1.00      1.25     1.50      1.75  \
0   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
1   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
2   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
3   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
4   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
5   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
6   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
7   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
8   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
9   0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
10  0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   
11  0.992141  0.996186  0.987884  0.983435  0.978811  0.97403  0.969106   

        2.00     2.25      2.50      4.00     7.50  
0   0.964055  0.95889  0.953623  0.920497  0.84014  
1   0.964055  0.95889  0.953623  0.920497  0.84014  
2   0.964055  0.95889  0.953623  0.920497  0.84014  
3   0.964055  0.95889  0.953623  0.920497  0.84014  
4   0.964055  0.95889  0.953623  0.920497  0.84014  
5   0.964055  0.95889  0.953623  0.920497  0.84014  
6   0.964055  0.95889  0.953623  0.920497  0.84014  
7   0.964055  0.95889  0.953623  0.920497  0.84014  
8   0.964055  0.95889  0.953623  0.920497  0.84014  
9   0.964055  0.95889  0.953623  0.920497  0.84014  
10  0.964055  0.95889  0.953623  0.920497  0.84014  
11  0.964055  0.95889  0.953623  0.920497  0.84014

In [169]:
swaprate2 = []

for m in range(12):
    w = (1-discountdata.loc[m][7.5]) / sum(discountdata.loc[m])*100
    swaprate2.append(w)

swaprate2

[0.93177349720703873,
 0.92946368210553854,
 0.90732828126414611,
 0.91880887573205194,
 0.92219453089777792,
 0.91875036389516851,
 0.9568538320565787,
 0.99834087736472188,
 1.0585742240915246,
 1.1478488032193459,
 1.228061695841302,
 1.3821982298341331]

In [170]:
PV01values = pd.DataFrame(discount2)[0]* swaprate2 - MTMvalues
PV01values

0    -0.002899
1    -0.002864
2    -0.002614
3    -0.001738
4    -0.001716
5    -0.001681
6    -0.001759
7    -0.001781
8    -0.001568
9    -0.000376
10   -0.000391
11   -0.000067
Name: 0, dtype: float64